"brewers" : [
	{
		"id" : "kalita-wave-185-glass-kit",
		"name" : "Kalita Wave 185 Glass Kit",
		"color" : [],
		"price" : 74.93,
		"discount": 15,
		"desc" : "We bundled so you can save up to 10% on select kits! The Kalita Wave 185 Glass Kit is ideal for brewing 16-26 oz of flavorful, full-bodied coffee. Designed with a flat-bottomed coffee bed, three small extraction holes, and a patented wave filter, the Kalita Wave dripper pulls a rich, evenly extracted, 2-4 cups (about 500-700ml). This convenient coffee kit includes everything you need to get started making the perfect cup of coffee at home! <img src=\"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/3.jpg\" Including this one of a kind copy of 33 Cups of Coffee! This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format. 33 Cups of Coffee is perfect for coffee aficionados, geeks, nerds, layabouts, and other fans of the roaster's art.",
		"img" : [
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/1.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/2.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/3.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/4.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/5.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-glass-kit/6.jpg",
		],
		"detail" : {
			"Brand" : "KALITA",
			"Includes" : "1 x Kalita Wave Glass Dripper Size 185",
			"" : "1 x Kalita Wave Filter for Size 185 Drippers, 100 Count",
			"" : "1x Kalita Glass Server with 500ml Capacity",
			"" : "1x This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
		},
	},
	{
		"id" : "yama-french-press-kit",
		"name" : "Yama French Press Kit",
		"color" : [],
		"price" : 84.18,
		"discount": 15,
		"desc" : "We bundled so you can save up to 10% on select kits! The Kalita Wave 185 Glass Kit is ideal for brewing 16-26 oz of flavorful, full-bodied coffee. Designed with a flat-bottomed coffee bed, three small extraction holes, and a patented wave filter, the Kalita Wave dripper pulls a rich, evenly extracted, 2-4 cups (about 500-700ml). This convenient coffee kit includes everything you need to get started making the perfect cup of coffee at home! <img src=\"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/2.jpg\" /> Including this one of a kind copy of 33 Cups of Coffee! This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format. 33 Cups of Coffee is perfect for coffee aficionados, geeks, nerds, layabouts, and other fans of the roaster's art.",
		"img" : [
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/1.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/2.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/3.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/4.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/5.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/6.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/yama-french-press-kit/7.jpg",
		],
		"detail" : {
			"Brand" : "YAMA",
			"Includes" : "1x (YAM0296C) Yama Glass French Press, 30oz Capacity",
			"" : "1x (YAMA25) Stainless Steel Kettle from Yama Glass, 24oz Capacity",
			"" : "1x (YAMES1) Bamboo Stir Stick, 9¾” Tall",
			"" : "1x (EP33BOOK) This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
		},
	},
	{
		"id" : "kalita-wave-style-kit",
		"name" : "Kalita Wave Style Kit",
		"color" : [],
		"price" : 73.08,
		"discount": 15,
		"desc" : "We bundled so you can save up to 10% on select kits! The Kalita Wave Style Kit is ideal for brewing 16-26 oz of flavorful, full-bodied coffee. Designed with a flat-bottomed coffee bed, three small extraction holes, and a patented wave filter, the Kalita Wave dripper pulls a rich, evenly extracted, 2-4 cups (about 500-700ml). This convenient coffee kit includes everything you need to get started making the perfect cup of coffee at home! The Kalita Wave Style Brewer brings a modern touch to the classic wave series aesthetic. Made with heat-resistant glass, a steel cage for the dripper, and a plastic grip, the Wave Style Brewer is perfect for brewing and serving. <img src \"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/4.jpg\" />Plus this one of a kind copy of 33 Cups of Coffee! This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format. 33 Cups of Coffee is perfect for coffee aficionados, geeks, nerds, layabouts, and other fans of the roaster's art.",
		"img" : [
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/1.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/2.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/3.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/4.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-style-kit/5.jpg",
		],
		"detail" : {
			"Brand" : "KALITA",
			"Includes" : "1 x (KWBREWER) Kalita Wave Style Set, Size 185",
			"" : "1 x (KW185F) Kalita Wave Filter for Size 185 Drippers, 100 Count",
			"" : "1 x (EP33BOOK) This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
		},
	},
	{
		"id" : "kalita-wave-185-kit",
		"name" : "Kalita Wave 185 Kit",
		"color" : [],
		"price" : 78.63,
		"discount": 15,
		"desc" : "We bundled so you can save up to 10% on select kits! The Kalita Wave 185 Kit is ideal for brewing 16-26 oz of flavorful, full-bodied coffee. Designed with a flat-bottomed coffee bed, three small extraction holes, and a patented wave filter, the Kalita Wave dripper pulls a rich, evenly extracted, 2-4 cups (about 500-700ml). This convenient coffee kit includes everything you need to get started making the perfect cup of coffee at home! <img src\"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/1.jpg\" /> Including this one of a kind copy of 33 Cups of Coffee! This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format. 33 Cups of Coffee is perfect for coffee aficionados, geeks, nerds, layabouts, and other fans of the roaster's art.",
		"img" : [
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/1.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/2.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/3.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/4.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/5.jpg",
			"/SGU_UDW1/_public/images/tools/brewers/kalita-wave-185-kit/6.jpg",
		],
		"detail" : {
			"Brand" : "KALITA",
			"Includes" : "1 x (KW185SS) Kalita Wave Stainless Steel Dripper Size 185",
			"" : "1 x (KW185F) Kalita Wave Filter for Size 185 Drippers, 100 Count.",
			"" : "1 x (KWSERVER) Kalita Glass Server with 500ml Capacity",
			"" : "1 x (EP33BOOK) This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
		},
	},
	{
		"id" : "kalita-copper-dripper-102",
		"name" : "Kalita Style Copper Dripper 102",
		"color" : [],
		"price" : 45.00,
		"discount": 0,
		"desc" : "The Kalita 102 Copper Dripper is a classic, straight-sided pour over dripper with a cone design, but with the iconic Kalita 3-hole extraction feature. Perfect for personal use at home, or by a professional barista in a coffee shop, this cone dripper will provide a balanced, evenly extracted cup of quality coffee. The 102 dripper fits most standard decanters, and brews up to 12oz (350ml) at a time.",
		"img" : [
			"/SGU_UDW1/_public/images/tools/brewers/kalita-copper-dripper-102.jpg",
		],
		"detail" : {
			"Brand" : "KALITA",
			"Base" : "4in diameter",
			"Liquid" : "8oz",
			"Requires" : "102 Filters",
		},
	},
],