var product = {
	"machine": [
		{
			"id" : "core-200",
			"name" : "Core 200",
			"color" : ["blue","black","white"],
			"price" : 7250,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/core200-500x500.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "core-600",
			"name" : "Core 600",
			"color" : ["blue","black","white"],
			"price" : 10.778,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/core600-500x500.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "greta",
			"name" : "Greta",
			"color" : ["red","white"],
			"price" : 2003,
			"discount" : 0,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/greta-500x500.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120/230/240V",
				"Rated power" : "1300/2400/2600W",
				"Heating Unit Capacity" : "2 / 0.44 lt / UK gal",
				"Tank Capacity" : "4 / 1.05 lt / UK gal",
				"Width" : "395 / 15.5 mm / in",
				"Depth" : "545 / 21.46 mm / in",
				"Height" : "511 / 20.08 mm / in",
				"Net weight": "	38 / 83.77 kg / lb",
				"Gross Weight": "47/104.62kg/lb",
			},
		},
		{
			"id" : "plus-4-you-ts",
			"name" : "Plus 4 You TS",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/plus4youts.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "230 - 400 V / 240 V",
				"Total power" : "4.400 W / 4.700 W",
				"Power per group" : "150 x 2 W / 165 x 2 W",
				"Water-coffee tank resistance power per group" : "1.000 x 2 W / 1.090 x 2 W",
				"Steam boiler power" :"3.000 W / 3.270 W",
				"Steam boiler capacity" : "8 / 1.76 lt / UK gal",
				"Water tank capacity" : "(1.2 / 0.26) x 2 lt / UK gal",
				"Width" : "835 / 32.9 mm / in",
				"Weight" : "84 / 185 kg / lb",
				"Depth" : "565 / 22.2 mm / in",
				"Height" : "575 / 22.6 mm / in",
			},
		},
		{
			"id" : "tanya-r",
			"name" : "Tanya R",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/tanyar.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120 / 230-400 / 240 V",
				"Power" : "2.200 / 2.900 / 3.200 W",
				"Heating Unit Capacity" : "6 / 1.3 lt / UK gal",
				"Width" : "505 / 19.9 mm / in",
				"Depth" : "535 / 21.1 mm / in",
				"Height" : "515 / 20.2 mm / in",
				"Net weight": "	44 / 97.00 kg / lb",
				"Gross Weight":"55/ 121.25 kg / lb",
			},
		},
	],
	"brewers": [
		{
			"id" : "kalita-wave-185-glass-kit",
			"name" : "KALITA WAVE 185 GLASS KIT",
			"color" : [],
			"price" : 74.93,
			"discount": 15,
			"img" : [
				"/SGU_UDW1/_public/images/tools/brewers/_1.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_2.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_3.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_4.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_5.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_6.jpg",
			],
			"detail" : {
				"Brand" : "KALITA",
				"Includes" : "1 x Kalita Wave Glass Dripper Size 185",
				"" : "1 x Kalita Wave Filter for Size 185 Drippers, 100 Count",
				"" : "1x Kalita Glass Server with 500ml Capacity",
				"" : "1x This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
			},
		},
	]
};
