var product = {
	"books": [
		{
			"id" : "coffee-for-life",
			"name" : "Coffee for life",
			"price" : 59,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/book/book1.png",
			],
			"desc" : "Coffee for Life is a great book written by T.L.A.",
			"detail" : {
				"Brand" : "Book",
				"Author" : "Team Laziest Animal",
				"SKU" : "EB11BOOK",
				"Size" : "short",
			},
		},
		{
			"id" : "the-best-coffee",
			"name" : "The best coffee",
			"price" : 49,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/book/book2.png",
			],
			"desc" : "The Best Coffee is a great book written by T.L.A.",
			"detail" : {
				"Brand" : "Book",
				"Author" : "Team Laziest Animal",
				"SKU" : "EB12BOOK",
				"Size" : "short",
			},
		},
		{
			"id" : "wanted-coffee",
			"name" : "Wanted Coffee",
			"price" : 59,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/book/book3.png",
			],
			"desc" : "Wanted Coffee is a great book written by T.L.A.",
			"detail" : {
				"Brand" : "Book",
				"Author" : "Team Laziest Animal",
				"SKU" : "EB13BOOK",
				"Size" : "short",
			},
		},
		{
			"id" : "f-j",
			"name" : "Food and Juice",
			"price" : 59,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/book/book4.png",
			],
			"desc" : "Food and Juice is a great book written by T.L.A.",
			"detail" : {
				"Brand" : "Book",
				"Author" : "Team Laziest Animal",
				"SKU" : "EB14BOOK",
				"Size" : "short",
			},
		},
	],
	"cups-and-mugs": [
		{
			"id" : "ep-porcelain",
			"name" : "EP PORCELAIN",
			"price" : 22,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/dinner-mug/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/dinner-mug/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/dinner-mug/3.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/dinner-mug/4.jpg",
			],
			"desc" : "The EP Porcelain diner coffee mug is a high-quality porcelain mug that has been manufactured to our exact specifications by one of the best porcelain manufacturers in the world.",
			"detail" : {
				"Brand" : "DINER MUG",
				"Material" : "porcelain",
				"Volumetric " : "305ml",
				"Fired " : "1300",
				
			},
		},
		{
			"id" : "demitasse",
			"name" : "DEMITASSE",
			"price" : 12,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/3.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/4.jpg",
			],
			"desc" : "The EP Porcelain diner coffee mug is a high-quality porcelain mug that has been manufactured to our exact specifications by one of the best porcelain manufacturers in the world.",
			"detail" : {
				"Brand" : "CUP & SAUCER BLACK WANTED",
				"Material" : "porcelain",
				"Volumetric " : "540ml",
				"Diameter" :"3.15\"",
			},
		},
		{
			"id" : "cup-and-saucer-black-wanted",
			"name" : "CUP & SAUCER BLACK WANTED",
			"price" : 12,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/3.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedblack/4.jpg",
			],
			"desc" : "The finish on these cafe cups is amazing and surpasses anything we ever imported from Europe.",
			"detail" : {
				"Brand" : "DEMITASSE",
				"Material" : "porcelain",
				"Volumetric " : "74ml",
				"Diameter" :"2.5\"",
			},
		},
		{
			"id" : "cup-and-saucer-creamy-white",
			"name" : "CUP & SAUCER CREAMY WHITE",
			"price" : 24,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedwhite/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedwhite/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedwhite/3.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/wantedwhite/4.jpg",
			],
			"desc" : "The finish on these cafe cups is amazing and surpasses anything we ever imported from Europe.",
			"detail" : {
				"Brand" : "DEMITASSE",
				"Material" : "porcelain",
				"Volumetric " : "148ml",
				"Diameter" :"2.5\"",
			},
		},
		{
			"id" : "mug-creamy-white",
			"name" : "MUG CREAMY WHITE",
			"price" : 29,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/cupwanted/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/cupwanted/2.jpg",
			],
			"desc" : "The finish on these cafe cups is amazing and surpasses anything we ever imported from Europe.",
			"detail" : {
				"Brand" : "DINER MUG",
				"Material" : "porcelain",
				"Volumetric " : "305ml",
				"Diameter" :"2.8\"",
			},
		},
		{
			"id" : "cupping-bowl",
			"name" : "CUPPING BOWL",
			"price" : 24,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/3.jpg",
			],
			"desc" : "Working with the Specialty Coffee Association (SCA), we have produced the next generation of cupping bowls.",
			"detail" : {
				"Brand" : "ESPRESSO PARTS",
				"Material" : "porcelain",
				"Volumetric " : "228 ml",
				"Diameter" :"3.15\"",
			},
		},
		{
			"id" : "cupping-bowl",
			"name" : "CUPPING BOWL",
			"price" : 24,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/1.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/2.jpg",
				"/SGU_UDW1/_public/images/tools/cupsandmugs/whitecup/3.jpg",
			],
			"desc" : "Working with the Specialty Coffee Association (SCA), we have produced the next generation of cupping bowls.",
			"detail" : {
				"Brand" : "ESPRESSO PARTS",
				"Material" : "porcelain",
				"Volumetric " : "228 ml",
				"Diameter" :"3.15\"",
			},
		},
	],
	"machine": [
		{
			"id" : "core-200",
			"name" : "Core 200",
			"color" : ["blue","black","white"],
			"price" : 7250,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/machine/core200-500x500.png",
			],
			"desc": "With Core200, espresso has a new design. Astoria’s heart beats inside Core, a blend of tradition, technology and passion for espresso. A solid and reliable product with a minimal and contemporary design.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "core-600",
			"name" : "Core 600",
			"color" : ["blue","black","white"],
			"price" : 10778,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/core600-500x500.png"],
			"desc" :"Core reinterprets the elegance of Astoria through simple lines and a modern shape that makes it immediately recognizable. With Core, the Italian tradition of espresso coffee is sublimated into a functional design object that can become the protagonist in every environment. Astoria’s heart beats inside Core600, a blend of tradition, technology and passion for espresso. With Core, espresso has a new design.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "greta",
			"name" : "Greta",
			"color" : ["red","white"],
			"price" : 2003,
			"discount" : 10,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/greta-500x500.png"],
			"desc" : "Great is the small versatile machine, suitable for both professional and semi-professional use.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120/230/240V",
				"Rated power" : "1300/2400/2600W",
				"Heating Unit Capacity" : "2 / 0.44 lt / UK gal",
				"Tank Capacity" : "4 / 1.05 lt / UK gal",
				"Width" : "395 / 15.5 mm / in",
				"Depth" : "545 / 21.46 mm / in",
				"Height" : "511 / 20.08 mm / in",
				"Net weight": "	38 / 83.77 kg / lb",
				"Gross Weight": "47/104.62kg/lb",
			},
		},
		{
			"id" : "plus-4-you-ts",
			"name" : "Plus 4 You TS",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/plus4youts.png"],
						"desc" : "Plus 4 You TS is a model that belongs to the Astoria high range that stands out for its dynamic and energetic lines that enhance excellent performance in terms of quality in the cup and energy saving.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "230 - 400 V / 240 V",
				"Total power" : "4.400 W / 4.700 W",
				"Power per group" : "150 x 2 W / 165 x 2 W",
				"Water-coffee tank resistance power per group" : "1.000 x 2 W / 1.090 x 2 W",
				"Steam boiler power" :"3.000 W / 3.270 W",
				"Steam boiler capacity" : "8 / 1.76 lt / UK gal",
				"Water tank capacity" : "(1.2 / 0.26) x 2 lt / UK gal",
				"Width" : "835 / 32.9 mm / in",
				"Weight" : "84 / 185 kg / lb",
				"Depth" : "565 / 22.2 mm / in",
				"Height" : "575 / 22.6 mm / in",
			},
		},
		{
			"id" : "tanya-r",
			"name" : "Tanya R",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/tanyar.png"],
			"desc": "With a simple yet harmonious aesthetics, durable materials and details optimized for professional use, Tanya R is the ideal solution for those looking for the essence of quality and the best combination of simplicity and reliability. Available in the SAE electronic version with volumetric dosage of 4 coffee doses, programmable directly from the keypad, and in the AEP semi-automatic version, with manual override button.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120 / 230-400 / 240 V",
				"Power" : "2.200 / 2.900 / 3.200 W",
				"Heating Unit Capacity" : "6 / 1.3 lt / UK gal",
				"Width" : "505 / 19.9 mm / in",
				"Depth" : "535 / 21.1 mm / in",
				"Height" : "515 / 20.2 mm / in",
				"Net weight": "	44 / 97.00 kg / lb",
				"Gross Weight":"55/ 121.25 kg / lb",
			},
		},
		{
			"id" : "pratic-avant",
			"name" : "Pratic Avant",
			"color" : ["black"],
			"price" : 4499,
			"discount" : 10,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/PraticAvant.png"],
			"desc" : "Distinguished by a simple and linear style, Pratic Avant is a model with slender and modern lines, for timeless taste. A soberly elegant design, embellished with shimmering chrome details that complete the character with an extremely refined look. All the Astoria experience and technology guarantee professional performance and high reliability for a final result of excellent beverage quality. Also available with raised groups option and new grids to support easily removable flap cups, in addition to lighting the large worktop.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "1120 / 230-400 / 240 V",
				" Power" : "2200 / 2900 / 3100 W",
				"Steam Heating Unit Capacity" : "6 / 1.3 lt / UK gal",
				"Width" : "560 / 22.0 mm / in",
				"Depth" : "560 / 22.0 mm / in",
				"Height" : "540 / 21.3 mm / in",
				"Net weight": "	59 / 130 kg / lb",
				"Gross Weight": "68 / 150 kg / lb",
			},
		},
		{
			"id" : "tanya-r-caps",
			"name" : "Tanya R Caps",
			"color" : ["black"],
			"price" : 2920,
			"discount" : 10,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/TanyaRCaps.png"],
			"desc" : "Tanya R Caps is the Astoria coffee machine perfect for low traffic areas, who want to offer their customers a good coffee in a comfortable and practical way.",
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : " 230 / 400 V",
				" Power" : "2300 / 2500 W",
				"Heating Unit Capacity" : "2 / 0.5 lt / UK gal",
				"Width" : "505 / 19.9 mm / in",
				"Depth" : "535 / 21.1 mm / in",
				"Height" : "515 / 20.2 mm / in",
				"Net weight": "	47 / 103.6 kg / lb",
				"Gross Weight": "58 / 127.8 kg / lb",
			},
		},
	],
	
	// "brewers": [
	// 	{
	// 		"id" : "kalita-wave-185-glass-kit",
	// 		"name" : "KALITA WAVE 185 GLASS KIT",
	// 		"color" : [],
	// 		"price" : 74.93,
	// 		"discount": 15,
	// 		"img" : [
	// 			"/SGU_UDW1/_public/images/tools/brewers/_1.jpg",
	// 			"/SGU_UDW1/_public/images/tools/brewers/_2.jpg",
	// 			"/SGU_UDW1/_public/images/tools/brewers/_3.jpg",
	// 			"/SGU_UDW1/_public/images/tools/brewers/_4.jpg",
	// 			"/SGU_UDW1/_public/images/tools/brewers/_5.jpg",
	// 			"/SGU_UDW1/_public/images/tools/brewers/_6.jpg",
	// 		],
	// 		"detail" : {
	// 			"Brand" : "KALITA",
	// 			"Includes" : "1 x Kalita Wave Glass Dripper Size 185",
	// 			"" : "1 x Kalita Wave Filter for Size 185 Drippers, 100 Count",
	// 			"" : "1x Kalita Glass Server with 500ml Capacity",
	// 			"" : "1x This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
	// 		},
	// 	},
	// ],
	
	"roasting" : [
		{
			"id" : "ascaso-steel-grinder-black",
			"name" : "Stell Flat Burr coffee Grinder",
			"color" : ["black"],
			"price" : 399,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/ascaso-steel-grinder-black.png"],
			"detail" : {
				"Brand" : "ASCASO",
				"Manufacturer": "Ascaso",
	 			"Width":    "5 inches",
				"Depth" : "9.5 inches",
				"Height":  "14.5 inches with hopper installed",
				"Watts": "250W",
				"Volts": "120V",
				"Programmability": "Manually adjusted grind",
				"Case Material" :"Aluminum",
				"Grinder Chamber":" Brass and Cast Aluminum",
				"Burrs":"54mm hardened steel w/ 1323lb service life (600kg)",
				"Hopper Capacity" :"250 grams",
				"RPM":"700",
				"Weight" :"7.7 pounds",
				"Auto Shut Off": "N/A",
				"Auto On": "N/A",
			},
		},
		{
			"id" : "mahlkonig-e65s-next-generation-matte-black",
			"name" : "Mahlkonig E65S Next Generation",
			"color" : ["black"],
			"price" : 2200,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-e65s-next-generation-matte-black.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1650 rpm (60 Hz)",
				"Grinding disc diameter": "65 mm / 2.56 in",
				"Grinding disc material": "Special steel",
				"Average grinding capacity*" : "4-7 g / s",
				"Hopper capacity": "ca. 1200 g / 2,64 lb",
				"Dimensions (w x h x d)": "19,5 × 58,3 × 28,3 cm",
				"Dimensions of packing (w x h x d)": "58,5 x 28,5 x 36,0 cm",
				"Net weight": "11,2 kg",
				"Gross weight": "12,7 kg",
				"Certifications": "CE, (CB), ETL 58,5 x 28,5 x 36,0 cm Safety, ETL Sanitation",
			},
		},
		{
			"id" : "mahlkonig-ek43-retail-grinder-black-mahlkoenig",
			"name" : "Mahlkonig EK43 Retail Grinder",
			"color" : ["black"],
			"price" : 2700,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-ek43-retail-grinder-black-mahlkoenig.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1760 rpm (60 Hz)",
				"Grinding disc diameter": "98 mm / 3.86 in",
				"Grinding disc material": "Cast steel",
				"Average grinding capacity*" : "ca. 25 g / s",
				"Hopper capacity": "ca. 1500 g / 3.31 lb",
				"Dimensions (w x h x d)": "23 x 77 x 41 cm",
				"Dimensions of packing (w x h x d)": "37 x 67 x 55 cm",
				"Net weight": "26 kg",
				"Gross weight": "30 kg",
				"Certifications": "CE, CB, ETL Safety, ETL Sanitation",
			},
		},
		{
			"id" : "bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity",
			"name" : "Bunn® G1 HD Bulk Bean Coffee Grinder - 1 Pound Capacityr",
			"color" : ["black"],
			"price" : 882,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity.png"],
			"detail" : { 
				"Brand" : "BUNN",
				"Features":"",
				"":"Bag switch stops motor when bag is removed and prevents grinding before bag is in place",
				"":"Turbo action draws coffee through grind chamber for greater grinding efficiency",
				"":"Wide range of grinds can be selected",
				"":"Convenient cleaning lever ensures complete clean out of coffee from grind chamber",
				"":"Four year warranty on grinding burrs",
				"":"Heavy-duty precision burrs for quality, finer grinds",
				"":"Single hopper holds 3lb (1.36kg) of regular, decaf or specialty coffee beans",
				"":"Fast grinding–one pound in under 30 seconds",
			},
		},
],
};
