var product = {
	"machine": [
		{
			"id" : "core-200",
			"name" : "Core 200",
			"color" : ["blue","black","white"],
			"price" : 7250,
			"discount" : 20,
			"img" : [
				"/SGU_UDW1/_public/images/tools/machine/core200-500x500.png",
			],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "core-600",
			"name" : "Core 600",
			"color" : ["blue","black","white"],
			"price" : 10778,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/core600-500x500.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "220-240V/380-415V",
				"Rated power" : "3.350W-3.900W",
				"Boiler" : "2.6 UK gal",
				"Water-steam wands	" : "1/2",
				"Width" : "29.4 in",
				"Depth" : "19.4 in",
				"Height" : "20.1 in",
				"Net Weight": "	148 lb",
			},
		},
		{
			"id" : "greta",
			"name" : "Greta",
			"color" : ["red","white"],
			"price" : 2003,
			"discount" : 10,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/greta-500x500.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120/230/240V",
				"Rated power" : "1300/2400/2600W",
				"Heating Unit Capacity" : "2 / 0.44 lt / UK gal",
				"Tank Capacity" : "4 / 1.05 lt / UK gal",
				"Width" : "395 / 15.5 mm / in",
				"Depth" : "545 / 21.46 mm / in",
				"Height" : "511 / 20.08 mm / in",
				"Net weight": "	38 / 83.77 kg / lb",
				"Gross Weight": "47/104.62kg/lb",
			},
		},
		{
			"id" : "plus-4-you-ts",
			"name" : "Plus 4 You TS",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/plus4youts.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "230 - 400 V / 240 V",
				"Total power" : "4.400 W / 4.700 W",
				"Power per group" : "150 x 2 W / 165 x 2 W",
				"Water-coffee tank resistance power per group" : "1.000 x 2 W / 1.090 x 2 W",
				"Steam boiler power" :"3.000 W / 3.270 W",
				"Steam boiler capacity" : "8 / 1.76 lt / UK gal",
				"Water tank capacity" : "(1.2 / 0.26) x 2 lt / UK gal",
				"Width" : "835 / 32.9 mm / in",
				"Weight" : "84 / 185 kg / lb",
				"Depth" : "565 / 22.2 mm / in",
				"Height" : "575 / 22.6 mm / in",
			},
		},
		{
			"id" : "tanya-r",
			"name" : "Tanya R",
			"color" : ["red,steel","white,black","gray,black"],
			"price" : 9680,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/tanyar.png"],
			"detail" : {
				"Brand" : "ASTORIA",
				"Voltage" : "120 / 230-400 / 240 V",
				"Power" : "2.200 / 2.900 / 3.200 W",
				"Heating Unit Capacity" : "6 / 1.3 lt / UK gal",
				"Width" : "505 / 19.9 mm / in",
				"Depth" : "535 / 21.1 mm / in",
				"Height" : "515 / 20.2 mm / in",
				"Net weight": "	44 / 97.00 kg / lb",
				"Gross Weight":"55/ 121.25 kg / lb",
			},
		},
	],
	"brewers": [
		{
			"id" : "kalita-wave-185-glass-kit",
			"name" : "KALITA WAVE 185 GLASS KIT",
			"color" : [],
			"price" : 74.93,
			"discount": 15,
			"img" : [
				"/SGU_UDW1/_public/images/tools/brewers/_1.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_2.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_3.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_4.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_5.jpg",
				"/SGU_UDW1/_public/images/tools/brewers/_6.jpg",
			],
			"detail" : {
				"Brand" : "KALITA",
				"Includes" : "1 x Kalita Wave Glass Dripper Size 185",
				"" : "1 x Kalita Wave Filter for Size 185 Drippers, 100 Count",
				"" : "1x Kalita Glass Server with 500ml Capacity",
				"" : "1x This coffee journal provides an easy way to quickly record coffee tasting notes in a small, convenient notebook format.",
			},
		},
	],
	"roasting" : [
		{
			"id" : "ascaso-steel-grinder-black",
			"name" : "Stell Flat Burr coffee Grinder",
			"color" : ["black"],
			"price" : 399,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/ascaso-steel-grinder-black.png"],
			"detail" : {
				"Brand" : "ASCASO",
				"Manufacturer": "Ascaso",
	 			"Width":    "5 inches",
				"Depth" : "9.5 inches",
				"Height":  "14.5 inches with hopper installed",
				"Watts": "250W",
				"Volts": "120V",
				"Programmability": "Manually adjusted grind",
				"Case Material" :"Aluminum",
				"Grinder Chamber":" Brass and Cast Aluminum",
				"Burrs":"54mm hardened steel w/ 1323lb service life (600kg)",
				"Hopper Capacity" :"250 grams",
				"RPM":"700",
				"Weight" :"7.7 pounds",
				"Auto Shut Off": "N/A",
				"Auto On": "N/A",
			},
		},
		{
			"id" : "mahlkonig-e65s-next-generation-matte-black",
			"name" : "Mahlkonig E65S Next Generation",
			"color" : ["black"],
			"price" : 2200,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-e65s-next-generation-matte-black.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1650 rpm (60 Hz)",
				"Grinding disc diameter": "65 mm / 2.56 in",
				"Grinding disc material": "Special steel",
				"Average grinding capacity*" : "4-7 g / s",
				"Hopper capacity": "ca. 1200 g / 2,64 lb",
				"Dimensions (w x h x d)": "19,5 × 58,3 × 28,3 cm",
				"Dimensions of packing (w x h x d)": "58,5 x 28,5 x 36,0 cm",
				"Net weight": "11,2 kg",
				"Gross weight": "12,7 kg",
				"Certifications": "CE, (CB), ETL 58,5 x 28,5 x 36,0 cm Safety, ETL Sanitation",
			},
		},
		{
			"id" : "mahlkonig-ek43-retail-grinder-black-mahlkoenig",
			"name" : "Mahlkonig EK43 Retail Grinder",
			"color" : ["black"],
			"price" : 2700,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-ek43-retail-grinder-black-mahlkoenig.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1760 rpm (60 Hz)",
				"Grinding disc diameter": "98 mm / 3.86 in",
				"Grinding disc material": "Cast steel",
				"Average grinding capacity*" : "ca. 25 g / s",
				"Hopper capacity": "ca. 1500 g / 3.31 lb",
				"Dimensions (w x h x d)": "23 x 77 x 41 cm",
				"Dimensions of packing (w x h x d)": "37 x 67 x 55 cm",
				"Net weight": "26 kg",
				"Gross weight": "30 kg",
				"Certifications": "CE, CB, ETL Safety, ETL Sanitation",
			},
		},
		{
			"id" : "bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity",
			"name" : "Bunn® G1 HD Bulk Bean Coffee Grinder - 1 Pound Capacityr",
			"color" : ["black"],
			"price" : 882,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity.png"],
			"detail" : { 
				"Brand" : "BUNN",
				"Features":"",
				"":"Bag switch stops motor when bag is removed and prevents grinding before bag is in place",
				"":"Turbo action draws coffee through grind chamber for greater grinding efficiency",
				"":"Wide range of grinds can be selected",
				"":"Convenient cleaning lever ensures complete clean out of coffee from grind chamber",
				"":"Four year warranty on grinding burrs",
				"":"Heavy-duty precision burrs for quality, finer grinds",
				"":"Single hopper holds 3lb (1.36kg) of regular, decaf or specialty coffee beans",
				"":"Fast grinding–one pound in under 30 seconds",
			},
		},
],
};
