{
		"id" : "ascaso-steel-uno-pid-black",
			"name" : "Stell Uno Programmable Espresso Machine W/PID Controller",
			"color" : ["black"],
			"price" : 1299,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/machine/core200-500x500.png"],
			"detail" : {
				"Brand" : "ASCASO",
				"Manufacturer": "Ascaso",
	 			"Width":    "11.25 inches",
				"Depth" : "2.5 inches/ 17 inches with the portafilter",
				"Height":  "15 inches",
				"Watts": "1100W",
				"Volts": "120V",
				"Programmability": "PID, Pre-infusion, Shot Time",
				"Case Material" :"Aluminum",
				"Boiler Material" :"Stainless Steel-lined Aluminum",
				"Cup Clearance": "3 inches",
				"Reservoir Size": "48 ounces",
				"Solenoid Valve": "Yes",
				"Cup Warmer": "Yes",
				"Portafilter": "Size 58mm",
				"Available Portafilters": "Bottomless, E.S.E Pods, Pressurized and Non-Pressurized",
				"Warm-Up: Brew Time": "3:30",
				"Boiler Design": "Thermoblock",
				"Pod Friendly": "Yes - without adaptation",
				"Water Sources": "Reservoir/Internal Tank",
				"Weight" :"7.7 pounds",
				"Auto Shut Off": "N/A",
				"Auto On": "No",
				"Pre-Infusion": "Yes",
				"Material" :"Aluminum",
				"Water Reservoir Material" :"Polycarbonate NSF and FDA approved for food purpose",
				"Flexible Tube Material": "Silicone",
				"Flowmeter Body Material" :"PBT (Arnite) 35%GF NSF compliant",
						},
	},
"roasting" : [
	{
		"id" : "ascaso-steel-grinder-black",
			"name" : "Stell Flat Burr coffee Grinder",
			"color" : ["black"],
			"price" : 399,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/ascaso-steel-grinder-black.png"],
			"detail" : {
				"Brand" : "ASCASO",
				"Manufacturer": "Ascaso",
	 			"Width":    "5 inches",
				"Depth" : "9.5 inches",
				"Height":  "14.5 inches with hopper installed",
				"Watts": "250W",
				"Volts": "120V",
				"Programmability": "Manually adjusted grind",
				"Case Material" :"Aluminum",
				"Grinder Chamber":" Brass and Cast Aluminum",
				"Burrs":"54mm hardened steel w/ 1323lb service life (600kg)",
				"Hopper Capacity" :"250 grams",
				"RPM":"700",
				"Weight" :"7.7 pounds",
				"Auto Shut Off": "N/A",
				"Auto On": "N/A",
						},
	},
	{
	"id" : "mahlkonig-e65s-next-generation-matte-black",
			"name" : "Mahlkonig E65S Next Generation",
			"color" : ["black"],
			"price" : 2200,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-e65s-next-generation-matte-black.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1650 rpm (60 Hz)",
				"Grinding disc diameter": "65 mm / 2.56 in",
				"Grinding disc material": "Special steel",
				"Average grinding capacity*" : "4-7 g / s",
				"Hopper capacity": "ca. 1200 g / 2,64 lb",
				"Dimensions (w x h x d)": "19,5 × 58,3 × 28,3 cm",
				"Dimensions of packing (w x h x d)": "58,5 x 28,5 x 36,0 cm",
				"Net weight": "11,2 kg",
				"Gross weight": "12,7 kg",
				"Certifications": "CE, (CB), ETL 58,5 x 28,5 x 36,0 cm Safety, ETL Sanitation",
				},
	},
	{
		"id" : "mahlkonig-ek43-retail-grinder-black-mahlkoenig",
			"name" : "Mahlkonig EK43 Retail Grinder",
			"color" : ["black"],
			"price" : 2700,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/mahlkonig-ek43-retail-grinder-black-mahlkoenig.png"],
			"detail" : {
				"Brand" : "MAHLKONIG",
				"Voltage" :  "220 - 240 V",
				"frequencies": "60 Hz",
				"phases": "1~",
				"Idle speed": "1760 rpm (60 Hz)",
				"Grinding disc diameter": "98 mm / 3.86 in",
				"Grinding disc material": "Cast steel",
				"Average grinding capacity*" : "ca. 25 g / s",
				"Hopper capacity": "ca. 1500 g / 3.31 lb",
				"Dimensions (w x h x d)": "23 x 77 x 41 cm",
				"Dimensions of packing (w x h x d)": "37 x 67 x 55 cm",
				"Net weight": "26 kg",
				"Gross weight": "30 kg",
				"Certifications": "CE, CB, ETL Safety, ETL Sanitation",
			},
	},
	{
		"id" : "bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity",
			"name" : "Bunn® G1 HD Bulk Bean Coffee Grinder - 1 Pound Capacityr",
			"color" : ["black"],
			"price" : 882,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/roasting/bunn-g1-hd-bulk-bean-coffee-grinder-1-pound-capacity.png"],
			"detail" : { 
				"Brand" : "BUNN",
				"Features":"",
								"":"Bag switch stops motor when bag is removed and prevents grinding before bag is in place",
								"":"Turbo action draws coffee through grind chamber for greater grinding efficiency",
								"":"Wide range of grinds can be selected",
								"":"Convenient cleaning lever ensures complete clean out of coffee from grind chamber",
								"":"Four year warranty on grinding burrs",
								"":"Heavy-duty precision burrs for quality, finer grinds",
								"":"Single hopper holds 3lb (1.36kg) of regular, decaf or specialty coffee beans",
								"":"Fast grinding–one pound in under 30 seconds",
						},
	},
],
"filters" :[
	{
		
		"id" : "kalita-102-paper-filter-white-40ct",
			"name" : "Bunn® G1 HD Bulk Bean Coffee Grinder - 1 Pound Capacityr",
			"color" : ["white"],
			"price" : 6,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/filters/kalita-102-paper-filter-white-40ct.png"],
			"detail" :{
						"Brand" : "KALITA",
						"Manufacturer":	"Kalita",
						"Size":	"Short (10 cm)",
						"Amuount" :"40",
			},
		},
		{
			"id" : "kalita-102-paper-filter-white-40ct",
			"name" : "Bunn® G1 HD Bulk Bean Coffee Grinder - 1 Pound Capacityr",
			"color" : ["white"],
			"price" : 6,
			"discount" : 20,
			"img" : ["/SGU_UDW1/_public/images/tools/filters/kalita-102-paper-filter-white-40ct.png"],
			"detail" :{
						"Brand" : "KALITA",
						"Manufacturer":	"Kalita",
						"Size":	"Short (10 cm)",
						"Amuount" :"40",
		},
	


],